### ISSUE TITLE
E/ViewRootImpl: sendUserActionEvent() mView == null

### ISSUE THREAD

**Issue by am1994** [udacity/andfun-kotlin-android-trivia#12]
when i click on menu "about"  this is error has shown "E/ViewRootImpl: sendUserActionEvent() mView == null" ,
 by the way i use samsung with kit kat android version

**Comment by CrudeRags** [comment]
The `About` button in the overflow menu does not work. Clicking it does not do anything.

**Comment by CrudeRags** [comment]
> The `About` button in the overflow menu does not work. Clicking it does not do anything.

When I deleted the branch and started anew, it worked fine. I don't know where the problem is
