### ISSUE TITLE
AndroidX implementation

### ISSUE THREAD

**Issue by DroidPulkit** [udacity/andfun-kotlin-android-trivia#14]
This project seems to use, old android versioning for navigation, thus, leading to lot's of confusion when on some exercise. Is there a way, we can rewrite the commit history and fix the versioning and move the code to proper AndroidX?

**Comment by DroidPulkit** [comment]
Anyone facing any problem use this :-

implementation "androidx.navigation:navigation-fragment-ktx:$version_navigation"
    implementation "androidx.navigation:navigation-ui-ktx:$version_navigation"

**Comment by DroidPulkit** [comment]
Any mods here, is it ok, if I send a PR and fix this?

**Comment by TheCodingArcher** [comment]
@DroidPulkit - even after upgrading or degrading the navigation dependency, it's not working at all.
Getting java.lang.IllegalArgumentException: No drawer view found with gravity LEFT in Exercise#9

**Comment by SudKul** [comment]
Stale issue. 
The repo has been updated multiple times since then.
