### ISSUE TITLE
Navigation drawer not closing

### ISSUE THREAD

**Issue by ravishankar97** [udacity/andfun-kotlin-android-trivia#19]
Navigation drawer once opened by pressing hamburger icon does not getting closed by pressing it again.

**Comment by Eslamelhoseiny** [comment]
override fun onBackPressed() {
        if (drawerLayout.isDrawerOpen(GravityCompat.START)) drawerLayout.closeDrawer(GravityCompat.START) else
            super.onBackPressed()
    }

**Comment by ravishankar97** [comment]
OnBackPressed is working fine. But the navigation drawer was not closing when I press the hamburger icon for the second time after opening.

**Comment by bupont** [comment]
Can confirm, wondering what the best solution is.

**Comment by shrishkukde** [comment]
The drawer is not closing after clicking on Hamburger Icon. Please suggest any solution.
