### ISSUE TITLE
Can't use safe args 

### ISSUE THREAD

**Issue by falconj-code** [udacity/andfun-kotlin-android-trivia#20]
After adding safe-args dependency and plugins, there are no generated class.
GameFragmentDirections doesn't show up.

When I type below code in GameFragment Kotlin file, an error shows up at GameFragmentDirections. The error says unresolved references
(screenshot as below)

![safe args issue](https://user-images.githubusercontent.com/43494533/80381572-b129b900-88d3-11ea-8256-1d485edd2c6d.png)

**Comment by sorianog** [comment]
@justinranger24 Make sure to `Rebuild Project` after adding the new dependencies. Update the versions in your Project gradle file as well if needed.

**Comment by justinranger24** [comment]
@sorianog It works after click Rebuild Project! Thanks a lot. 
I only clicked  `clean project` and stuck in this for quite some time...
