### ISSUE TITLE
Can't add "layout_gravity" property to NavigationView in DrawerLayout

### ISSUE THREAD

**Issue by Lakshyasukhralia** [udacity/andfun-kotlin-android-trivia#21]
I get the following exception while clicking on hamburger icon:
**java.lang.IllegalArgumentException: No drawer view found with gravity LEFT**

Here is the activity_main.xml:

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.drawerlayout.widget.DrawerLayout
        android:id="@+id/drawer"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            tools:context=".MainActivity">

            <fragment
                android:id="@+id/myNavHostFragment"
                android:name="androidx.navigation.fragment.NavHostFragment"
                app:defaultNavHost="true"
                app:navGraph="@navigation/navigation"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

        </LinearLayout>

        <com.google.android.material.navigation.NavigationView
            android:id="@+id/navView"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            app:menu="@menu/navdrawer_menu" />
    </androidx.drawerlayout.widget.DrawerLayout>
</layout>

Regards

**Comment by raihan38** [comment]
Hello @Lakshyasukhralia , I was having the same problem.Then I pasted android:layout_gravity="start|left" inside of my NavigationView, even if the suggestion doesn't show up, when you write the code,it is accepted. so finally my Navigation view is something like this 
`<com.google.android.material.navigation.NavigationView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/navigationview"
        app:headerLayout="@layout/header"
        app:menu="@menu/navenu"
        android:layout_gravity="start|left"
        />`
Hope it helps.

**Comment by kastrahl** [comment]
thanks

**Comment by Wjy-yyds** [comment]
I have the same problem. Thank you

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors. Threads in the https://knowledge.udacity.com/ platform are helpful to new students.

**Comment by SudKul** [comment]
The current start code in the master branch seems to already have the `android:layout_gravity="start"` attribute:

```
       <com.google.android.material.navigation.NavigationView
            android:id="@+id/navView"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            app:headerLayout="@layout/nav_header"
            app:menu="@menu/navdrawer_menu" />
    </androidx.drawerlayout.widget.DrawerLayout>
```
