### ISSUE TITLE
Gradle sync failure.  Could not find androidx.navigation:navigation-safe-args-gradle-plugin:1.0.0-alpha07.

### ISSUE THREAD

**Issue by njwarfield** [udacity/andfun-kotlin-android-trivia#24]
Cloned the repository.  On sync the following occurs:

Could not find androidx.navigation:navigation-safe-args-gradle-plugin:1.0.0-alpha07.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/androidx/navigation/navigation-safe-args-gradle-plugin/1.0.0-alpha07/navigation-safe-args-gradle-plugin-1.0.0-alpha07.pom
  - https://jcenter.bintray.com/androidx/navigation/navigation-safe-args-gradle-plugin/1.0.0-alpha07/navigation-safe-args-gradle-plugin-1.0.0-alpha07.pom
Required by:
    project :

![image](https://user-images.githubusercontent.com/9011248/91257914-a58ab980-e730-11ea-967d-9a369f5b9e28.png)

**Comment by crayonwriter** [comment]
Try adding this to the dependencies in the build.gradle:

def nav_version = "2.3.0-alpha01"
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

**Comment by njwarfield** [comment]
Thanks.  Updating to that version I was able to successfully sync.  I'm hoping everything works correctly with a major version change.
