### ISSUE TITLE
GameWonFragment compiler error when passing fragment in ShareCompat.IntentBuilder.from()

### ISSUE THREAD

**Issue by PierreBou91** [udacity/andfun-kotlin-android-trivia#25]
In GameWonFragment, in the fun getShareIntent the line:
```
return ShareCompat.IntentBuilder.from(activity)
                .setText(getString(R.string.share_success_text, args.numCorrect, args.numQuestions))
                .setType("text/plain")
                .intent
```
gives the error:
"Type mismatch. Required: Activity, Found: Fragment Activity?"
![image](https://user-images.githubusercontent.com/50236624/92303059-c98c9d00-ef71-11ea-8903-211a1e61e472.png)

Error is in starter code branch, and Step 11 Solution Branch so I guess it is in every branch but I have not checked yet.

**Comment by Sicabou** [comment]
`private fun getShareIntent() : Intent {
        val args = GameWonFragmentArgs.fromBundle(requireArguments())
        val shareIntent = Intent(Intent.ACTION_SEND)
        shareIntent.setType("text/plain")
                .putExtra(Intent.EXTRA_TEXT,
                        getString(R.string.share_success_text, args.numCorrect, args.numQuestions))
        return shareIntent
    }`

this function makes it work. It should be updated in the Github repo :)

**Comment by Sicabou** [comment]
Actually, shareCompat is the problem. I'm not sure how it changed since the course was created so I cannothelp fixing it. Stopping BEFORE it's required to use it works fine, as above.

**Comment by aricnappi** [comment]
Casting `activity` to `Activity` (i.e. replacing `activity` with `activity as Activity`) seems to work.

**Comment by SudKul** [comment]
Hey @Sicabou 
I tried running the step 11 solution. It is working fine.  
Is it working for you as well?

**Comment by Adarsh-Adk** [comment]
use (activity!!) instead of (activity)

**Comment by mhmdcs** [comment]
@Adarsh-Adk's fix is good, alternatively, you could also use requireActivity() rather than activity or activity!!.
