### ISSUE TITLE
Any way to remove action bar on some fragments?

### ISSUE THREAD

**Issue by natiginfo** [udacity/andfun-kotlin-android-trivia#3]
Hi,
Watched tutorials and implemented on my project. I wonder if there is any way to hide action bar on some fragments?

**Comment by natiginfo** [comment]
Thank you! I'll close the issue now.

**Comment by ksoundarya4** [comment]
how to hide bottom action bar when new fragment opens?

**Comment by IsaiasCuvula** [comment]
> ### Add this to your fragment's onCreateActivity:
> ### (activity as AppCompatActivity).supportActionBar?.hide()

I use it now, and works thank you very much

**Comment by NimaaZx** [comment]
Thanks to @jheske , I think there should be a better way to do this while there are many fragments. using a interface . I don't know exactly how it can be used when we have inner fragment, I mean when they are opened up and "replace" each other.

**Comment by clerdson** [comment]
sorry,in my case with two fragments hide action bar,help me

**Comment by majedul123** [comment]
(activity as AppCompatActivity?)!!.getSupportActionBar()!!.hide()

**Comment by rishabhsingh2002** [comment]
> (activity as AppCompatActivity?)!!.getSupportActionBar()!!.hide()

where is the onCreateActivity method in fragments? I am not able to implement??
