### ISSUE TITLE
Gradle sync failure. Failure to resolve - android.arch.navigation:navigation-fragment-ktx:2.3.0, - android.arch.navigation:navigation-ui-ktx:2.3.0

### ISSUE THREAD

**Issue by leminhduc1202** [udacity/andfun-kotlin-android-trivia#36]

**Comment by leminhduc1202** [comment]
So i download and open , when i sync this show up : 

Failed to resolve: android.arch.navigation:navigation-fragment-ktx:2.3.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: android.arch.navigation:navigation-ui-ktx:2.3.0
Show in Project Structure dialog
Affected Modules: app

![image](https://user-images.githubusercontent.com/79216758/126871519-8d10d2b4-11d1-49f3-8fb8-740738aa9e34.png)

Hope someone help me !

**Comment by lamhh171** [comment]
I've also come across the same problem but managed to fix it. 
I think the issue is different versions used, try changing the code to 

classpath **"androidx.navigation:navigation-safe-args-gradle-plugin:$version_navigation"**
