### ISSUE TITLE
Is Android Studio 3.4 required to build the project?

### ISSUE THREAD

**Issue by godixyz** [udacity/andfun-kotlin-android-trivia#4]

**Comment by cmhuert1** [comment]
I am also having trouble building the project. Do we need to download from the Canary branch of Android Studio?

**Comment by hramovecchi** [comment]
I just download AS 3.2, clone the repo and the build was unsuccessfull.

**Comment by menzelths** [comment]
Confirming the problem: gradle running with AS 3.2.1 says that I should try to open the project with AS 3.4.

**Comment by hramovecchi** [comment]
Gradle version is required to be 5.0 and with AS 3.2 Gradle is 4.6. I've upgrade to version 5.0 but builds problems still persists

**Comment by godixyz** [comment]
@hramovecchi you need Android Studio 3.4 Canary

**Comment by cmhuert1** [comment]
@godixyz You got it to build ok? I installed Canary and I still have issues saying my gradle-plugin version is wrong. I've messed around with the build files, but I haven't had any luck.

**Comment by jheske** [comment]
We are currently recommending AS 3.3 for projects.  

These settings will work in the current 3.3 beta version with two small changes to your project:

In build.gradle (Project), change gradle version to 3.3.0-rc02

In menu go to File -> Project Structure.  There you can change the gradle version to 4.10.0

**Comment by cmhuert1** [comment]
@jheske Thank you for the response.

**Comment by godixyz** [comment]
Hi @cmhuert1 did you tried ?

**Comment by godixyz** [comment]
Okay it's ok I get it to build with @jheske settings but it's gradle version 4.10.3 coz 4.10.0 distro actually doesnt exist. Happy coding :heart:

**Comment by lenniezelk** [comment]
i followed @jheske and @godixyz instructions but also had to update Android Plugin Version to 3.2.1 for it to run under File -> Project Structure -> Project

**Comment by Semeruk** [comment]
AS 3.4 doesn't give any error, I'll stay with it as the project required.

**Comment by jheske** [comment]
AS 3.3 RC3 is the latest release, is tested, and recommended for all projects.   You are free to use later versions if you wish, but it isn't required, and can sometimes result in incompatibilities with other library versions.

This configuration should work with AS 3.3 RC3.  It may not include all the libs for your particular app.  Some versions aren't the latest but they are tested and work.

    ext {
        kotlinVersion = '1.3.11'
        archLifecycleVersion = '1.1.1'
        gradleVersion = '3.3.0-rc03'
        navigationVersion = '1.0.0-alpha07'
        supportlibVersion = '1.0.0-rc03'
        dataBindingCompilerVersion = gradleVersion // Always need to be the same.
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$gradleVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
    }

build.gradle(app)

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation "com.google.android.material:material:$supportlibVersion"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation "android.arch.navigation:navigation-fragment-ktx:$navigationVersion"
    implementation "android.arch.navigation:navigation-ui-ktx:$navigationVersion"
}

**Comment by finnerjones** [comment]
this is turning into a bit of a version nightmare ... 
Am I the only one?

`Step.02-Exercise-Lets-Navigate-Already` nor `Step.02-Solution-Lets-Navigate-Already` are not building for me. 

When I build either of the branches Android Studio suggests an Android Gradle Plugin upgrade to `3.3.0-rc03` and now the following error is appearing
`ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.`. 

So, I have to upgrade Kotlin?

Shouldn't this code **work out of the box** ? I am spending more time with version issues than actually getting through the material. 

I am on AS 3.3 RC 3 and have Android SDK 28
Anyone know what I am supposed to have installed?

**Comment by jheske** [comment]
Versions can be a moving target.  We try our best to document changes.

Android Studio 3.3 is the latest stable version and is recommended for all projects.

Use gradle plugin 3.3.0
Upgrade Kotlin to 1.3.11

**Comment by finnerjones** [comment]
Thank you very much @jheske !! That has fixed my issues !!!
