### ISSUE TITLE
NavigationUp

### ISSUE THREAD

**Issue by aungzinphyo94** [udacity/andfun-kotlin-android-trivia#6]
val navController = this.findNavController(R.id.myNavHostFragment)

For this code, below error is showing:
" 

Type mismatch: inferred type is Int but View was expected |  
-- | --

"

**Comment by Semeruk** [comment]
I got another error: 
![screen shot 2019-01-08 at 5 01 40 pm](https://user-images.githubusercontent.com/16003589/50838627-2849df80-1367-11e9-984d-14a35f4e78bd.png)

> Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.navigation.NavController$OnNavigatedListener"

Activity doesn't want to start.
Did someone figure this out?

**Comment by jheske** [comment]
I'm assuming you're using AS 3.3.0-rc03.  There are a few things you can try:

-Check whether you changed anything other than the exercise's TODOs.  
-If you're not using the Exercise starter code, check its branch out and try the exercise again.
-Check out the solution branch and try it.  If it works, compare it with yours.  
-Also, there could be some incompatibilities in build.gradle.  Try copying the build.gradle files from the solution code and see if it works.

**Comment by Semeruk** [comment]
@jheske you were right, I compared with the solution code and found a couple of differences in build.gradle files. Thanks!
