### ISSUE TITLE
Incompatible Kotlin/Gradle Version on Branch Step.01-Exercise-Creating-and-Adding-a-Fragment

### ISSUE THREAD

**Issue by tdvoss** [udacity/andfun-kotlin-android-trivia#7]
Branch Step.01-Exercise-Creating-and-Adding-a-Fragment had gradle errors for me. Android Studio forced upgrade of Gradle to 3.3.0 and then I made changes to upgrade the Kotlin version so that the kotlin-gradle-plugin was supported. I've attached a patch file of the changes.
[0001-Update-gradle-and-kotlin-versions.zip](https://github.com/udacity/andfun-kotlin-android-trivia/files/2932225/0001-Update-gradle-and-kotlin-versions.zip)

**Comment by dnkilic** [comment]
All the branches have the same issue.

![Screen Shot 2019-03-11 at 10 56 00](https://user-images.githubusercontent.com/10210360/54099549-678ac000-43ec-11e9-8915-5c369b49df34.png)

ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
root project 'andfun-kotlin-android-trivia' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51
Affected Modules: app

**Comment by jheske** [comment]
It's pretty typical for Android Studio, gradle, and Kotlin versions change periodically.  You can accept the automatic gradle plugin update.  The Kotlin version you will have to update yourself in build.grade.  

If build fails and AS shows you a "The specified Gradle distribution 'https://services.gradle.org/distributions/gradle-xxx.zip' does not exist, you can update it on the Project Structure screen.  Select menu option File | Project Structure. Under Project, enter the new Gradle version (in your case 4.10.1.

**Comment by Offpics** [comment]
@dnkilic 
> Anyone face with this issue can do update the following lines in app/build.gradle;
> 
> kotlin_version = '1.3.21'
> classpath 'com.android.tools.build:gradle:3.3.2'

For clarification those lines are in **project** build.gradle
